apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-discord.fullname" . }}
  labels:
    {{- include "alertmanager-discord.labels" . | nindent 4 }}
stringData:
  DISCORD_WEBHOOK: {{ required "You must specify .config.discordWebhook" .Values.config.discordWebhook }}

