{{- if and .Values.kubeconfig.enabled (or (eq .Values.kubeconfig.type "cleartext") (eq .Values.kubeconfig.type "encoded")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssl-exporter.kubeconfigSecret" . }}
  labels:
    {{- include "ssl-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.kubeconfig.type "encoded" }}
  config: {{ required "You need to define the value 'kubeconfig.b64data'" .Values.kubeconfig.b64data }}
  {{- else if eq .Values.kubeconfig.type "cleartext" }}
  config: {{ required "You need to define the value 'kubeconfig.data'" .Values.kubeconfig.data | b64enc }}
  {{- end }}
{{- end }}
