apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovirt-exporter.fullname" . }}-credentials
type: Opaque
stringData:
  password: {{ required "You must specify 'config.api.password'" .Values.config.api.password }}
