{{- if not (and .Values.config.api.passwordSecret.name .Values.config.api.passwordSecret.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovirt-exporter.secret.credentials.name" . }}
type: Opaque
stringData:
  password: {{ required "You must specify 'config.api.password'" .Values.config.api.password }}
{{- end }}
